### ISSUE TITLE
是不是暂时不支持Android模拟器

### ISSUE THREAD

**Issue by zx900930** [Jinnrry/RobotHelper#15]
模拟器 网易Mumu
Android: 6.0.1
ExecTypeAccessibillty 无障碍
Accessibility状态：已加载
opencv加载成功
取点成功
然后执行点击的时候 提示
![image](https://user-images.githubusercontent.com/734749/91423993-850a4e80-e859-11ea-9860-c77c7ffc5d35.png)
获得无障碍权限后重启过模拟器还是一样的提权错误
是不是无障碍也只支持Android 7 或者8 以上的？
PS: Android 10 无障碍 一点启动直接死机，log停留在opencv加载成功

**Comment by Jinnrry** [comment]
无障碍必须安卓7以上，安卓6的话没法用

模拟器建议用用root或者xposed方式点击吧

android10死机是在模拟器上面吗？我开发也是在android10上面，我没遇到过，能复现的我可以看看

**Comment by zx900930** [comment]
Android 10 
死机发生在实体机器上
logcat执行到点击就卡死
08/27 12:34:55: Launching 'app' on Xiaomi Mi A2 Lite.
```
$ adb shell am start -n "cn.xjiangwei.RobotHelper/cn.xjiangwei.RobotHelper.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Connected to process 13472 on device 'xiaomi-mi_a2_lite-c396c28a0305'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
I/Perf: Connecting to perf service.
W/wei.RobotHelpe: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
W/wei.RobotHelpe: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
D/OpenCV/StaticHelper: Trying to get library list
E/OpenCV/StaticHelper: OpenCV error: Cannot load info library for OpenCV
D/OpenCV/StaticHelper: Library list: ""
    First attempt to load libs
    Trying to init OpenCV libs
    Trying to load library opencv_java3
D/OpenCV/StaticHelper: Library opencv_java3 loaded
    First attempt to load libs is OK
I/OpenCV/StaticHelper: General configuration for OpenCV 3.4.1 =====================================
      Version control:               3.4.1
      Platform:
        Timestamp:                   2018-02-23T12:15:01Z
        Host:                        Linux 4.13.0-32-generic x86_64
        Target:                      Linux 1 aarch64
        CMake:                       2.8.12.2
        CMake generator:             Ninja
        CMake build tool:            /usr/bin/ninja
        Configuration:               Release
      CPU/HW features:
        Baseline:                    NEON
          requested:                 NEON FP16
          required:                  NEON
          disabled:                  VFPV3
      C/C++:
        Built as dynamic libs?:      NO
        C++ Compiler:                /usr/bin/ccache /opt/android/android-ndk-r10e/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-g++ (ver 4.9)
        C++ flags (Release):         -fexceptions -frtti -Wno-psabi --sysroot=/opt/android/android-ndk-r10e/platforms/android-21/arch-arm64 -funwind-tables -fsigned-char -no-canonical-prefixes -fdata-sections -ffunction-sections -Wa,--noexecstack  -DANDROID -D__ANDROID_API__=21   -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-comment -fdiagnostics-show-option -fomit-frame-pointer   -fvisibility=hidden -fvisibility-inlines-hidden -fomit-frame-pointer -fstrict-aliasing -funswitch-loops -finline-limit=300 -O3 -DNDEBUG  -DNDEBUG
        C++ flags (Debug):           -fexceptions -frtti -Wno-psabi --sysroot=/opt/android/android-ndk-r10e/platforms/android-21/arch-arm64 -funwind-tables -fsigned-char -no-canonical-prefixes -fdata-sections -ffunction-sections -Wa,--noexecstack  -DANDROID -D__ANDROID_API__=21   -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-comment -fdiagnostics-show-option -fomit-frame-pointer   -fvisibility=hidden -fvisibility-inlines-hidden -fno-omit-frame-pointer -fno-strict-aliasing -O0 -g -DDEBUG -D_DEBUG  -DDEBUG -D_DEBUG
        C Compiler:                  /usr/bin/ccache /opt/android/android-ndk-r10e/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-gcc
        C flags (Release):           -fexceptions -Wno-psabi --sysroot=/opt/android/android-ndk-r10e/platforms/android-21/arch-arm64 -funwind-tables -fsigned-char -no-canonical-prefixes -fdata-sections -ffunction-sections -Wa,--noexecstack  -DANDROID -D__ANDROID_API__=21   -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wuninitialized -Winit-self -Wno-narrowing -Wno-comment -fdiagnostics-show-option -fomit-frame-pointer   -fvisibility=hidden -fomit-frame-pointer -fstrict-aliasing -funswitch-loops -finline-limit=300 -O3 -DNDEBUG  -DNDEBUG
        C flags (Debug):             -fexceptions -Wno-psabi --sysroot=/opt/android/android-ndk-r10e/platforms/android-21/arch-arm64 -funwind-tables -fsigned-char -no-canonical-prefixes -fdata-sections -ffunction-sections -Wa,--noexecstack  -DANDROID -D__ANDROID_API__=21   -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wuninitialized -Winit-self -Wno-narrowing -Wno-comment -fdiagnostics-show-option -fomit-frame-pointer   -fvisibility=hidden -fno-omit-frame-pointer -fno-strict-aliasing -O0 -g -DDEBUG -D_DEBUG  -DDEBUG -D_DEBUG
        Linker flags (Release):      -Wl,--no-undefined -Wl,--gc-sections -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now    
        Linker flags (Debug):        -Wl,--no-undefined -Wl,--gc-sections -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now    
        ccache:                      YES
        Precompiled headers:         NO
        Extra dependencies:          z dl m log
        3rdparty dependencies:       libjpeg libwebp libpng libtiff libjasper IlmImf libprotobuf libcpufeatures tegra_hal tbb
      OpenCV modules:
        To be built:                 calib3d core dnn features2d flann highgui imgcodecs imgproc java java_bindings_generator ml objdetect photo python_bindings_generator shape stitching superres video videoio videostab
        Disabled:                    js world
        Disabled by dependency:      -
        Unavailable:                 cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev python2 python3 ts viz
        Applications:                android_examples
        Documentation:               NO
        Non-free algorithms:         NO
      Android: 
        Android ABI:                 arm64-v8a
        STL type:                    gnustl_static
        Native API level:            android-21
        SDK target:                  android-21
        Android NDK:                 /opt/android/android-ndk-r10e (toolchain: aarch64-linux-android-4.9)
        android tool:                /opt/android/android-sdk-java7/tools/android (Android SDK Tools, revision 25.2.2.)
      GUI: 
      Media I/O: 
        ZLib:                        z (ver 1.2.3)
        JPEG:                        build (ver 90)
        WEBP:                        build (ver encoder: 0x020e)
        PNG:                         build (ver 1.6.34)
        TIFF:                        build (ver 42 - 4.0.9)
        JPEG 2000:                   build (ver 1.900.1)
        OpenEXR:                     build (ver 1.7.1)
      Video I/O:
      Parallel framework:            TBB (ver 2018.0 interface 10001)
I/OpenCV/StaticHelper:   Trace:                         YES (built-in)
      Other third-party libraries:
        Custom HAL:                  YES (carotene (ver 0.0.1))
        Protobuf:                    build (3.5.1)
      Python (for build):            /usr/bin/python2.7
      Java:                          export all functions
        ant:                         /usr/bin/ant (ver 1.9.3)
        Java wrappers:               YES
        Java tests:                  NO
      Install to:                    /build/master_pack-android/build/o4a/install
    -----------------------------------------------------------------
I/AdrenoGLES: QUALCOMM build                   : 7c13572, I09ac334ad9
    Build Date                       : 09/26/19
    OpenGL ES Shader Compiler Version: EV031.27.05.01
    Local Branch                     : 
    Remote Branch                    : 
    Remote Branch                    : 
    Reconstruct Branch               : 
    Build Config                     : S L 8.0.11 AArch64
I/AdrenoGLES: PFP: 0x005ff110, ME: 0x005ff066
W/Gralloc3: mapper 3.x is not supported
W/wei.RobotHelper: type=1400 audit(0.0:544331): avc: granted { search } for name="/" dev="mmcblk0p57" ino=2 scontext=u:r:untrusted_app_27:s0:c215,c256,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir
W/Binder:13472_3: type=1400 audit(0.0:544337): avc: granted { search } for name="/" dev="mmcblk0p57" ino=2 scontext=u:r:untrusted_app_27:s0:c215,c256,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir
W/wei.RobotHelper: type=1400 audit(0.0:544494): avc: granted { search } for name="/" dev="mmcblk0p57" ino=2 scontext=u:r:untrusted_app_27:s0:c215,c256,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir
```

**Comment by zx900930** [comment]
PS：测试雷电模拟器
Android 7.1可以正常的识图+点击，但是toast显示不出来，而且会崩溃
```
I/Tesseract(native): Initialized Tesseract API with language=chi_sim
E/AndroidRuntime: FATAL EXCEPTION: Thread-2
    Process: cn.xjiangwei.RobotHelper, PID: 3173
    java.lang.IllegalArgumentException: Path bounds must not be negative
        at android.accessibilityservice.GestureDescription$StrokeDescription.<init>(GestureDescription.java:229)
        at cn.xjiangwei.RobotHelper.Tools.InputImp.AccessibilityInput.tap(AccessibilityInput.java:41)
        at cn.xjiangwei.RobotHelper.Tools.InputImp.AccessibilityInput.tap(AccessibilityInput.java:65)
        at cn.xjiangwei.RobotHelper.Tools.Robot.tap(Robot.java:101)
        at cn.xjiangwei.RobotHelper.GamePackage.Main.start(Main.java:72)
        at cn.xjiangwei.RobotHelper.Service.RunTime$ButtonBroadcastReceiver$1.run(RunTime.java:155)

```

**Comment by Jinnrry** [comment]
```
I/Tesseract(native): Initialized Tesseract API with language=chi_sim
E/AndroidRuntime: FATAL EXCEPTION: Thread-2
    Process: cn.xjiangwei.RobotHelper, PID: 3173
    java.lang.IllegalArgumentException: Path bounds must not be negative
        at android.accessibilityservice.GestureDescription$StrokeDescription.<init>(GestureDescription.java:229)
        at cn.xjiangwei.RobotHelper.Tools.InputImp.AccessibilityInput.tap(AccessibilityInput.java:41)
        at cn.xjiangwei.RobotHelper.Tools.InputImp.AccessibilityInput.tap(AccessibilityInput.java:65)
        at cn.xjiangwei.RobotHelper.Tools.Robot.tap(Robot.java:101)
        at cn.xjiangwei.RobotHelper.GamePackage.Main.start(Main.java:72)
        at cn.xjiangwei.RobotHelper.Service.RunTime$ButtonBroadcastReceiver$1.run(RunTime.java:155)
```


这个报错是因为你tap函数传入了小于0的坐标，Toast是可以显示的，因为tap那里抛异常了，导致没执行到后面

**Comment by zx900930** [comment]
> ```
> I/Tesseract(native): Initialized Tesseract API with language=chi_sim
> E/AndroidRuntime: FATAL EXCEPTION: Thread-2
>     Process: cn.xjiangwei.RobotHelper, PID: 3173
>     java.lang.IllegalArgumentException: Path bounds must not be negative
>         at android.accessibilityservice.GestureDescription$StrokeDescription.<init>(GestureDescription.java:229)
>         at cn.xjiangwei.RobotHelper.Tools.InputImp.AccessibilityInput.tap(AccessibilityInput.java:41)
>         at cn.xjiangwei.RobotHelper.Tools.InputImp.AccessibilityInput.tap(AccessibilityInput.java:65)
>         at cn.xjiangwei.RobotHelper.Tools.Robot.tap(Robot.java:101)
>         at cn.xjiangwei.RobotHelper.GamePackage.Main.start(Main.java:72)
>         at cn.xjiangwei.RobotHelper.Service.RunTime$ButtonBroadcastReceiver$1.run(RunTime.java:155)
> ```
> 
> 这个报错是因为你tap函数传入了小于0的坐标，Toast是可以显示的，因为tap那里抛异常了，导致没执行到后面

确实，我图片是损坏的，没有返回值导致tap点空了。 7.1的Accessibility测试一切正常 👌

**Comment by Jinnrry** [comment]
在模拟器上面root模式无法使用是因为sendevent工具我默认使用的arm64架构编译的。模拟器的话你需要切换成x86或者x64架构的文件，切换位置在`cn/xjiangwei/RobotHelper/Tools/InputImp/RootInput.java:882` ，对应的二进制文件我已经编译一份提交了，你更新一下代码就能看到了

**Comment by zx900930** [comment]
@Jinnrry 
借地儿问一下：如果要启动别的app应该怎么写？
还有UI设置之类的写在哪？

**Comment by Jinnrry** [comment]
启动其他app的话用Intent就行了

UI你要怎么设置？写自己的界面吗？目前布局文件都在https://github.com/Jinnrry/RobotHelper/tree/master/Android/app/src/main/res/layout

**Comment by zx900930** [comment]
> 启动其他app的话用Intent就行了
> 
> UI你要怎么设置？写自己的界面吗？目前布局文件都在https://github.com/Jinnrry/RobotHelper/tree/master/Android/app/src/main/res/layout

谢谢！ 就是这个Accessibility模式运行一段时间以后会自己断掉，不知道其它软件是怎么解决这个问题的。

**Comment by Jinnrry** [comment]
能打个日志看下吗？看下断掉是不是AccessibilityService挂掉了？

理论上来说，应用进程没有被杀的话AccessibilityService应该都在
