### ISSUE TITLE
识别图片的时候出现了之前没有出现过的问题

### ISSUE THREAD

**Issue by Cheng77777** [Jinnrry/RobotHelper#20]
![image](https://user-images.githubusercontent.com/30279763/94450057-6217e500-01df-11eb-86e7-5a2502b88314.png)

**Comment by Cheng77777** [comment]
E/Xposed: de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.android.server.input.InputManagerService
        at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:71)
        at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:260)
        at cn.xjiangwei.RobotHelper.Xposed.Hook4Input.hook4LTandroid10(Hook4Input.java:63)
        at cn.xjiangwei.RobotHelper.Xposed.Hook4Input.run(Hook4Input.java:19)
        at cn.xjiangwei.RobotHelper.Xposed.Main.handleLoadPackage(Main.java:17)
        at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
        at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
        at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106)
        at de.robv.android.xposed.XposedInit$2.beforeHookedMethod(XposedInit.java:134)
        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:340)
        at android.app.ActivityThread.handleBindApplication(<Xposed>)
        at android.app.ActivityThread.-wrap1(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1414)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5539)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635)
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
     Caused by: java.lang.ClassNotFoundException: com.android.server.input.InputManagerService
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:324)
        at external.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:823)
        at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:69)
        at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:260) 
        at cn.xjiangwei.RobotHelper.Xposed.Hook4Input.hook4LTandroid10(Hook4Input.java:63) 
        at cn.xjiangwei.RobotHelper.Xposed.Hook4Input.run(Hook4Input.java:19) 
        at cn.xjiangwei.RobotHelper.Xposed.Main.handleLoadPackage(Main.java:17) 
        at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34) 
        at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61) 
        at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106) 
        at de.robv.android.xposed.XposedInit$2.beforeHookedMethod(XposedInit.java:134) 
        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:340) 
        at android.app.ActivityThread.handleBindApplication(<Xposed>) 
        at android.app.ActivityThread.-wrap1(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1414) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5539) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635) 
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.server.input.InputManagerService" on path: DexPathList[[zip file "/data/app/cn.xjiangwei.RobotHelper-2/base.apk"],nativeLibraryDirectories=[/data/app/cn.xjiangwei.RobotHelper-2/lib/x86, /data/app/cn.xjiangwei.RobotHelper-2/base.apk!/lib/x86, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:324) 
        at external.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:823) 
        at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:69) 
        at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:260) 
        at cn.xjiangwei.RobotHelper.Xposed.Hook4Input.hook4LTandroid10(Hook4Input.java:63) 
        at cn.xjiangwei.RobotHelper.Xposed.Hook4Input.run(Hook4Input.java:19) 
        at cn.xjiangwei.RobotHelper.Xposed.Main.handleLoadPackage(Main.java:17) 
        at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34) 
        at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61) 
        at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106) 
        at de.robv.android.xposed.XposedInit$2.beforeHookedMethod(XposedInit.java:134) 
        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:340) 
        at android.app.ActivityThread.handleBindApplication(<Xposed>) 
        at android.app.ActivityThread.-wrap1(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1414) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5539) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635) 
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107) 
    	Suppressed: java.lang.ClassNotFoundException: Didn't find class "com.android.server.input.InputManagerService" on path: DexPathList[[dex file "/data/dalvik-cache/xposed_XResourcesSuperClass.dex", dex file "/data/dalvik-cache/xposed_XTypedArraySuperClass.dex"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 24 more
    		Suppressed: java.lang.ClassNotFoundException: com.android.server.input.InputManagerService
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        			... 25 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

**Comment by Jinnrry** [comment]
这个应该不影响程序运行吧？
你手机android版本是多少，是xposed没hook到类

**Comment by Cheng77777** [comment]
我用的网易MUMU模拟器测试的，我重装模拟器之后这个问题解决了，但是今天又出现了同样的问题，不知道是不是Xposed的问题

**Comment by Jinnrry** [comment]
@bigursa  能定位下是什么功能导致的吗？是tap还是，图片相关操作

**Comment by Jinnrry** [comment]
@bigursa  https://github.com/Jinnrry/RobotHelper/blob/master/Android/app/src/main/java/cn/xjiangwei/RobotHelper/Xposed/Main.java#L14

尝试注释掉这3个hook函数，看看还会崩溃不

**Comment by bigursa** [comment]
2022-01-19 14:52:14.266 6570-6570/? I/art: Late-enabling -Xcheck:jni
2022-01-19 14:52:14.267 6570-6570/? D/libnativebridge: call UnloadNativeBridge! state=1
2022-01-19 14:52:14.443 6570-6570/com.xyz.RobotHelper I/art: Starting a blocking GC Xposed
2022-01-19 14:52:14.449 6570-6570/com.xyz.RobotHelper E/Xposed: de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.android.server.input.InputManagerService
        at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:71)
        at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:260)
        at com.xyz.RobotHelper.Xposed.Hook4Input.hook4LTandroid10(Hook4Input.java:63)
        at com.xyz.RobotHelper.Xposed.Hook4Input.run(Hook4Input.java:19)
        at com.xyz.RobotHelper.Xposed.Main.handleLoadPackage(Main.java:17)

**Comment by bigursa** [comment]
上面是我遇到的问题，因为同样有 java.lang.ClassNotFoundException: com.android.server.input.InputManagerService
这个异常，还以为是遇到同样的问题。就目前来看和截图点击没关系，只要程序退出就会现出这个异常，比如点击下拉通知中的退出，也会出来这个异常。我这边程序退出应当是特定游戏给杀掉了，然后又引发了这个异常。
不过在这过程中也遇到一个问题
https://github.com/Jinnrry/RobotHelper/blob/master/Android/app/src/main/java/cn/xjiangwei/RobotHelper/Tools/ScreenCaptureUtil.java
ScreenCaptureUtilByMediaPro.getScreenCapVertical()
这个方法中 bitmapCacheVertical.recycle()
ScreenCaptureUtilByMediaPro.getScreenCapHorizontal()
这个方法中 bitmapCacheHorizontal.recycle()

这两句会偶尔引发程序异常 trying to use a recycled bitmap 提示应用重启
我这将原来的
//        if (bitmapCacheVertical != null) {
//            bitmapCacheVertical.recycle();
//            bitmapCacheVertical = null;
//        }

改成现在这样
  if (bitmapCacheVertical != null && !bitmapCacheVertical.isRecycled()) {
            //bitmapCacheVertical.recycle();
            bitmapCacheVertical = null;
     }

**Comment by Jinnrry** [comment]
> 上面是我遇到的问题，因为同样有 java.lang.ClassNotFoundException: com.android.server.input.InputManagerService 这个异常，还以为是遇到了同样的问题。就目前来看和点击没关系，只要程序退出异常出这个异常，比如点击通知中的退出，就会出现这个异常。然后我这个程序退出了这个应该是某个特定的游戏，又出现了这个异常。 不过在这个过程中也发生了。一个问题方法 https://github.com/Jinnrry/RobotHelper/blob/master/Android/app/src/main/java/cn/xjiangwei/RobotHelper/Tools/ScreenCaptureUtil.java ScreenCaptureUtilByMediaPro.getScreenCapVertical() 这个中的bitmapCacheVertical.recycle () ScreenCaptureUtilByMediaPro.getScreenCapHorizo​​ntal() 这个方法中 bitmapCacheHorizo​​ntal.recycle()
> 
> 语句会出现一个bitmapCacheVertical 启动 异常 // bitmapCacheVertical = null; // }
> 
> 改成现在这样 if (bitmapCacheVertical != null && !bitmapCacheVertical.isRecycled()) { //bitmapCacheVertical.recycle(); bitmapCacheVertical = null; }

多谢，这个确实是一个bug，我合到主分支去
