### ISSUE TITLE
无法在逍遥模拟器Android7.1.2版本使用

### ISSUE THREAD

**Issue by chongkaechin** [Jinnrry/RobotHelper#26]
目前我有写了几个脚本，在雷电模拟器可以使用，但是我在逍遥模拟器上却出现RobotHelper停止运行的情况。想麻烦作者看看问题出在哪里，能不能解决。

**Comment by Jinnrry** [comment]
有报错信息吗

**Comment by chongkaechin** [comment]
![image](https://user-images.githubusercontent.com/59221468/98247636-d730c400-1fae-11eb-9503-d17deccef693.png)
![image](https://user-images.githubusercontent.com/59221468/98247685-edd71b00-1fae-11eb-992d-e60c86b5d5d6.png)

**Comment by chongkaechin** [comment]
问题好像出在tap函数

**Comment by chongkaechin** [comment]
2020-11-05 21:36:01.724 2558-3195/cn.xjiangwei.RobotHelper E/ImageReader_JNI: Producer output buffer format: 0x2, ImageReader configured format: 0x1
2020-11-05 21:36:01.725 2558-3195/cn.xjiangwei.RobotHelper E/AndroidRuntime: FATAL EXCEPTION: Thread-2
    Process: cn.xjiangwei.RobotHelper, PID: 2558
    java.lang.UnsupportedOperationException: The producer output buffer format 0x2 doesn't match the ImageReader's configured buffer format 0x1.
        at android.media.ImageReader.nativeImageSetup(Native Method)
        at android.media.ImageReader.acquireNextSurfaceImage(ImageReader.java:340)
        at android.media.ImageReader.acquireNextImage(ImageReader.java:394)
        at android.media.ImageReader.acquireLatestImage(ImageReader.java:287)
        at cn.xjiangwei.RobotHelper.Tools.ScreenCaptureUtilByMediaPro.getScreenCap(ScreenCaptureUtilByMediaPro.java:82)
        at cn.xjiangwei.RobotHelper.Tools.ScreenCaptureUtil.getScreenCap(ScreenCaptureUtil.java:22)
        at cn.xjiangwei.RobotHelper.GamePackage.LoginAccount.SearchBMP(Main.java:53)
        at cn.xjiangwei.RobotHelper.GamePackage.Main.start(Main.java:135)
        at cn.xjiangwei.RobotHelper.Service.RunTime$ButtonBroadcastReceiver$1.run(RunTime.java:154)
2020-11-05 21:36:01.801 529-2513/system_process I/OpenGLRenderer: Initialized EGL, version 1.4
2020-11-05 21:36:01.801 529-2513/system_process D/OpenGLRenderer: Swap behavior 1
2020-11-05 21:36:01.801 529-2513/system_process E/EGL_adreno: CreateContext rcMajorVersion:3, minorVersion:0
2020-11-05 21:36:01.802 529-2513/system_process D/EGL_adreno: eglCreateContext: 0xb24cbc00: maj 3 min 0 rcv 3
2020-11-05 21:36:05.170 529-2480/system_process W/SchedPolicy: add_tid_to_cgroup failed to write '1043' (Permission denied); fd=25
2020-11-05 21:36:49.224 1320-1368/com.android.vending I/PlayCommon: [111] assq.h(22): Preparing logs for uploading
2020-11-05 21:36:49.230 1320-1368/com.android.vending I/PlayCommon: [111] assq.h(132): Connecting to server for timestamp: https://play.googleapis.com/play/log/timestamp
2020-11-05 21:36:49.378 1320-1368/com.android.vending I/PlayCommon: [111] assq.h(166): Connecting to server: https://play.googleapis.com/play/log?format=raw&proto_v2=true
2020-11-05 21:36:49.493 1320-1368/com.android.vending I/PlayCommon: [111] assq.h(198): Successfully uploaded logs.
2020-11-05 21:36:59.530 529-670/system_process W/SchedPolicy: add_tid_to_cgroup failed to write '1143' (Permission denied); fd=4
2020-11-05 21:36:59.548 529-740/system_process W/SchedPolicy: add_tid_to_cgroup failed to write '1143' (Permission denied); fd=25
2020-11-05 21:37:06.745 1043-2300/com.google.android.gms I/PlayCommon: [140] gva.b: Preparing logs for uploading
2020-11-05 21:37:06.762 1043-2300/com.google.android.gms I/PlayCommon: [140] gva.b: Connecting to server for timestamp: https://play.googleapis.com/play/log/timestamp
2020-11-05 21:37:06.863 1043-2300/com.google.android.gms W/PlayCommon: [140] gva.a: No account for auth token provided
2020-11-05 21:37:06.863 1043-2300/com.google.android.gms I/PlayCommon: [140] gva.b: Connecting to server: https://play.googleapis.com/play/log?format=raw&proto_v2=true
2020-11-05 21:37:06.922 1043-2300/com.google.android.gms I/PlayCommon: [140] gva.b: Successfully uploaded logs.
2020-11-05 21:37:10.220 529-578/system_process W/WifiMode: aslkutn376, Invalid SupportedRates!!!
2020-11-05 21:37:10.220 529-581/system_process W/WifiMode: aslkutn376, Invalid SupportedRates!!!
2020-11-05 21:37:10.221 529-578/system_process W/WifiMode: aslkutn376, Invalid SupportedRates!!!
2020-11-05 21:37:42.436 3493-3493/? V/StudioTransport: Server listening on 127.0.0.1:12389 port:1238

**Comment by chongkaechin** [comment]
是要这个东西吗，我对android studio还不熟悉

**Comment by Jinnrry** [comment]
你是使用什么模式运行的？能贴下报错代码吗

**Comment by Jinnrry** [comment]
找到了，是逍遥模拟器里面截图api返回格式不对。
cn/xjiangwei/RobotHelper/Tools/ScreenCaptureUtilByMediaPro.java:55
cn/xjiangwei/RobotHelper/Tools/ScreenCaptureUtilByMediaPro.java:42

你可以找到这两个地方，
`
ImageReader.newInstance(MainApplication.sceenWidth, MainApplication.sceenHeight,
                PixelFormat.RGBX_8888, 2);
`

把图片格式改成RGBX

**Comment by Jinnrry** [comment]
https://github.com/omerjerk/Screenshotter/issues/1

这里有类似的讨论，估计只能针对不同的手机或者模拟器单独去适配，没啥通用的解决方案
