### ISSUE TITLE
图片匹配报错

### ISSUE THREAD

**Issue by louis2610** [Jinnrry/RobotHelper#38]
2021-01-23 15:56:58.623 31535-32038/? E/cv::error(): OpenCV(3.4.1) Error: Assertion failed (info.format == ANDROID_BITMAP_FORMAT_RGBA_8888 || info.format == ANDROID_BITMAP_FORMAT_RGB_565) in void Java_org_opencv_android_Utils_nBitmapToMat2(JNIEnv*, jclass, jobject, jlong, jboolean), file /build/master_pack-android/opencv/modules/java/generator/src/cpp/utils.cpp, line 37
	2021-01-23 15:56:58.624 31535-32038/? E/org.opencv.android.Utils: nBitmapToMat caught cv::Exception: OpenCV(3.4.1) /build/master_pack-android/opencv/modules/java/generator/src/cpp/utils.cpp:37: error: (-215) info.format == ANDROID_BITMAP_FORMAT_RGBA_8888 || info.format == ANDROID_BITMAP_FORMAT_RGB_565 in function void Java_org_opencv_android_Utils_nBitmapToMat2(JNIEnv*, jclass, jobject, jlong, jboolean)
	2021-01-23 15:56:58.624 31535-32038/? E/AndroidRuntime: FATAL EXCEPTION: Thread-4
	    Process: cn.xjiangwei.RobotHelper, PID: 31535
	    CvException [org.opencv.core.CvException: OpenCV(3.4.1) /build/master_pack-android/opencv/modules/java/generator/src/cpp/utils.cpp:37: error: (-215) info.format == ANDROID_BITMAP_FORMAT_RGBA_8888 || info.format == ANDROID_BITMAP_FORMAT_RGB_565 in function void Java_org_opencv_android_Utils_nBitmapToMat2(JNIEnv*, jclass, jobject, jlong, jboolean)
	    ]
	        at org.opencv.android.Utils.nBitmapToMat2(Native Method)
	        at org.opencv.android.Utils.bitmapToMat(Utils.java:93)
	        at org.opencv.android.Utils.bitmapToMat(Utils.java:102)
	        at cn.xjiangwei.RobotHelper.Tools.Image.matchTemplate(Image.java:417)
	        at cn.xjiangwei.RobotHelper.GamePackage.Main.start(Main.java:46)
	        at cn.xjiangwei.RobotHelper.Service.RunTime.lambda$new$0(RunTime.java:12)
	        at cn.xjiangwei.RobotHelper.Service.-$$Lambda$RunTime$RDwjJ76_1WI5ryoCtkMEOSbuaCo.run(Unknown Source:0)
	        at java.lang.Thread.run(Thread.java:919)

**Comment by Jinnrry** [comment]
这个报错看起来是你图片格式不对，一个图片是RGBA8888,而另外一个是RGB565

**Comment by Jinnrry** [comment]
https://github.com/Jinnrry/RobotHelper/issues/26

应该和这个是同一个问题

**Comment by louis2610** [comment]
图片格式改成RGBX也不行啊

**Comment by Jinnrry** [comment]
你是模拟器吗，有复现代码吗

**Comment by Jinnrry** [comment]
https://stackoverflow.com/questions/22043430/i-got-cvexception-by-bitmaptomat-on-android

你看下你的模板图片是不是RGBA格式的，你先试试换个模板
