### ISSUE TITLE
尝试使用回收的位图错误如何解决？

### ISSUE THREAD

**Issue by cpg868** [Jinnrry/RobotHelper#40]
问题描述：在ScreenCaptureUtil.getScreenCap时，有时会抛出如下错误
2021-01-26 23:19:11.760 2294-3396/cn.xjiangwei.RobotHelper E/AndroidRuntime: FATAL EXCEPTION: Thread-12
    Process: cn.xjiangwei.RobotHelper, PID: 2294
    java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@f8ae68c
        at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1271)
        at android.graphics.Canvas.drawBitmap(Canvas.java:1368)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:807)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:701)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:681)
        at cn.xjiangwei.RobotHelper.Tools.ScreenCaptureUtil.getScreenCap(ScreenCaptureUtil.java:49)
        at cn.xjiangwei.RobotHelper.Tools.ScreenCaptureUtil.getScreenCap(ScreenCaptureUtil.java:108)
        at cn.xjiangwei.RobotHelper.GamePackage.Main$9.run(Main.java:617)
        at java.lang.Thread.run(Thread.java:761)

**Comment by Jinnrry** [comment]
是物理机还是虚拟机？啥型号的，有复现方法吗，我周末试试

**Comment by cpg868** [comment]
雷电虚拟机，64位，安卓7.1.2,
复现方法
```
        new Thread(new Runnable() {
            @Override
            public void run() {
                String stone = "";
                while (true) {
                    stone = TessactOcr.img2string(ScreenCaptureUtil.getScreenCap(358, 506, 375, 523), "chi_sim", "石", "");
                    if (StringUtils.isNotBlank(stone)) {
                        MLog.info("文字识别："+stone);
                    }
                    sleep(100);
                }
            }
        }).start();
```
长时间运行时就会报错。

**Comment by Jinnrry** [comment]
长时间运行是多长时间？我跑了半个多小时都没复现出来

**Comment by Jinnrry** [comment]
看了一下代码，我猜测是虚拟机内存不够，系统把图片资源的内存回收掉了，因此出了这个错误。

你试试把虚拟机内存调大点呢。

**Comment by Jinnrry** [comment]
#41 你拉这个分支的代码试试，我添加了一个校验
